server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false #当前服务不需要在eureka上注册
    fetch-registry: false #不需要从eureka服务器获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   # Eureka客户端设置Eureka Server的地址
logging:
  config: classpath:logback.xml


